@first_net_HostAddress = http://localhost:5130

GET {{first_net_HostAddress}}

###
POST {{first_net_HostAddress}}/user
###
GET {{first_net_HostAddress}}/products

###
GET {{first_net_HostAddress}}/api/categories?searchValue=apple
 
###
POST  {{first_net_HostAddress}}/api/categories
Content-Type:application/json

{
    "name" : "apple",
    "description":"This is good"
}

###
PUT  {{first_net_HostAddress}}/api/categories/bffac798-53e3-4032-9e10-a272a6ee76c8
Content-Type: application/json

{
         "name" : "a",
         "description" : "Net Description"
}
 
###
DELETE  {{first_net_HostAddress}}/api/categories/3f2504e0-4f89-11d3-9a0c-0305e82c3301
 
